- name: Docker Stacks | create home directory for docker stacks
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ docker_stacks_owner }}"
    group: "{{ docker_stacks_group }}"
    mode: "0755"
  with_items:
    - "{{ docker_stacks_dir }}"

- name: Docker Stacks | Stacks service template
  ansible.builtin.template:
    src: docker-stack@.service.j2
    dest: "{{ docker_stacks_dir }}/docker-stack@.service"
    owner: "{{ docker_stacks_owner }}"
    group: "{{ docker_stacks_group }}"
    mode: "0644"

- name: Docker Stacks | enable stacks service
  ansible.builtin.file:
    src: "{{ docker_stacks_dir }}/docker-stack@.service"
    dest: "/etc/systemd/system/docker-stack@.service"
    state: link
    owner: root
    group: root
    mode: "0644"

- name: Stack | Dockge installation
  ansible.builtin.include_tasks:
    file: docker-stack.yml
  when: docker_stacks_dockge_install
